### ISSUE TITLE
Portrait layout on mobile has overlapping elements

### ISSUE THREAD

**Issue by SimpleProgrammingAU** [SimpleProgrammingAU/CovidVaultDash#26]
I will note that the UI components I am using were supposed to make the menu a dropdown on mobile, but that functionality appears to be stuck in the "dropped down" position.

Workaround: please use a desktop to access the dashboard in the interim.

**Comment by TomBTR** [comment]
This problem also occurs on the desktop. Tried with Firefox and Chrome on XP and Chrome on Windows 10.

**Comment by SimpleProgrammingAU** [comment]
@TomBTR can I ask a couple of follow-up questions because I have not been able to recreate that behaviour on a desktop-sized layout:

- what resolution is your screen?
- was it a particular view (eg: Analytics) where the problem appeared? Or was it in all views?
- are there particular steps I can follow to recreate the overlap?

As far as I have been able to tell so far, overlapping only occurs when you get below about 650px in display width.

**Comment by TomBTR** [comment]
1440x900
I think that it is all views. See screenshot below.

**Comment by SimpleProgrammingAU** [comment]
@TomBTR the screenshot didn't come through =(

**Comment by SimpleProgrammingAU** [comment]
From TomBTR:

![image](https://user-images.githubusercontent.com/10446022/97634848-84c14600-1a8a-11eb-95c3-4ca5e50e6999.png)

The cause is the lack of a `max-width` property being applied to the sidebar or heading.

**Comment by SimpleProgrammingAU** [comment]
@TomBTR the merged pull request https://github.com/SimpleProgrammingAU/CovidVaultDash/pull/27 contains the fix to limit the width of the sidebar to prevent the overlap shown in the screenshot above.

Please let me know if the issue persists.
